// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// W
NumericVector W(NumericVector lam, NumericVector nu, int sumTo);
RcppExport SEXP CompGLM_W(SEXP lamSEXP, SEXP nuSEXP, SEXP sumToSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type lam(lamSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP );
        Rcpp::traits::input_parameter< int >::type sumTo(sumToSEXP );
        NumericVector __result = W(lam, nu, sumTo);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// Y
NumericVector Y(NumericVector lam, NumericVector nu, int sumTo);
RcppExport SEXP CompGLM_Y(SEXP lamSEXP, SEXP nuSEXP, SEXP sumToSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type lam(lamSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP );
        Rcpp::traits::input_parameter< int >::type sumTo(sumToSEXP );
        NumericVector __result = Y(lam, nu, sumTo);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// Z
NumericVector Z(NumericVector lam, NumericVector nu, int sumTo);
RcppExport SEXP CompGLM_Z(SEXP lamSEXP, SEXP nuSEXP, SEXP sumToSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type lam(lamSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP );
        Rcpp::traits::input_parameter< int >::type sumTo(sumToSEXP );
        NumericVector __result = Z(lam, nu, sumTo);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// dcomp
NumericVector dcomp(IntegerVector y, NumericVector lam, NumericVector nu, int sumTo = 100, bool logP = false);
RcppExport SEXP CompGLM_dcomp(SEXP ySEXP, SEXP lamSEXP, SEXP nuSEXP, SEXP sumToSEXP, SEXP logPSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP );
        Rcpp::traits::input_parameter< NumericVector >::type lam(lamSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP );
        Rcpp::traits::input_parameter< int >::type sumTo(sumToSEXP );
        Rcpp::traits::input_parameter< bool >::type logP(logPSEXP );
        NumericVector __result = dcomp(y, lam, nu, sumTo, logP);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// pcomp
NumericVector pcomp(IntegerVector q, NumericVector lam, NumericVector nu, int sumTo = 100, bool lowerTail = true, bool logP = false);
RcppExport SEXP CompGLM_pcomp(SEXP qSEXP, SEXP lamSEXP, SEXP nuSEXP, SEXP sumToSEXP, SEXP lowerTailSEXP, SEXP logPSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< IntegerVector >::type q(qSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type lam(lamSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type nu(nuSEXP );
        Rcpp::traits::input_parameter< int >::type sumTo(sumToSEXP );
        Rcpp::traits::input_parameter< bool >::type lowerTail(lowerTailSEXP );
        Rcpp::traits::input_parameter< bool >::type logP(logPSEXP );
        NumericVector __result = pcomp(q, lam, nu, sumTo, lowerTail, logP);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// rcomp
IntegerVector rcomp(int n, double lam, double nu, int sumTo = 100);
RcppExport SEXP CompGLM_rcomp(SEXP nSEXP, SEXP lamSEXP, SEXP nuSEXP, SEXP sumToSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< int >::type n(nSEXP );
        Rcpp::traits::input_parameter< double >::type lam(lamSEXP );
        Rcpp::traits::input_parameter< double >::type nu(nuSEXP );
        Rcpp::traits::input_parameter< int >::type sumTo(sumToSEXP );
        IntegerVector __result = rcomp(n, lam, nu, sumTo);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
